### PR TITLE
fix #30 - check if raw input is None before calling get_raw_not_managed

### LINKED ISSUE #10: created patch-file not correct
When trying to convert my handwritten docstrings to something more consisting I ran into a corrupted patch-file. I attached a shortened patch-file and the corresponding original file that reproduce the bug. I was using pyment v0.3.0 with Python 2.7.6 (in a WinPython distribution).

1) As you can see, the whole docstring is supposed to be changed to convert `'''` to `"""`. But only the first line of the new docstring is marked with `+`, the other 3 lines are not marked, ergo they are treated as context that should be equal in both files. Therefore the line count of the hunk does not fit anymore and the patching fails.
2) Also note that the last 3 lines got an extra whitespace in the beginning of the line. This is not present in the original file.
3) As a side-note: pyment creates an `a/` and an `b/` in the beginning of the paths of source and target of the patch. Note that these are not the actual folders of the files. I executed pyment in the folder of the file. Comparing with patches created from `diff`, I would guess that you could just omit this behavior.

I do not think it is of importance here, but note that I am using pyment on Windows 7.

**patchfile** (created running `pyment __init__short.py` in the same folder as `__init__short.py`)

``` diff
# Patch generated by Pyment v0.3.0

--- a/__init__ short.py
+++ b/__init__ short.py
@@ -12,12 +12,7 @@


 def init_test():
-    '''
-    Only working when in WinPython root directory.
-    
-    Returns:
-    maske, data0, data1, no_motion, motion
-    '''
+    """Only working when in WinPython root directory.

    Returns:
    maske, data0, data1, no_motion, motion"""

     maske = read_mask('./MRR/Testdaten/55_mask.bmp')
     display(maske)
     data0 = read_dicom_set('./MRR/Testdaten/188_13-12-10_56_1',

```

**original file:**

``` python
# -*- coding: utf-8 -*-

__version__ = '1.3.1'
# $Source$

#Some commentary


from .mod1 import *
#import mod2
from . import mod3, mod4


def init_test():
    '''
    Only working when in WinPython root directory.

    Returns:
    maske, data0, data1, no_motion, motion
    '''
    maske = read_mask('./MRR/Testdaten/55_mask.bmp')
    display(maske)
    data0 = read_dicom_set('./MRR/Testdaten/188_13-12-10_56_1',
                               unwrap=True, mask=maske, verbose=False)
    data1 = read_dicom_set('./MRR/Testdaten/188_13-12-10_54_1',
                               unwrap=True, mask=maske, verbose=False)
    no_motion = mean(data0, axis=0)
    motion = mean(data1, axis=0)
    return maske , data0, data1, no_motion, motion

```

edit: files now reproduce the bug.

### LINKED ISSUE #30: AttributeError: 'NoneType' object has no attribute 'split'
I am using `Python 3.6.0` and `Pyment v0.3.2`.

When running `pyment -c pyment.conf test.py` with

**pyment.conf**
```
first_line = true
quotes = '''
output_style = numpydoc
input_style = numpydoc
init2class = true
```

**test.py**
```python
def hello_world():
  return 42
```

I get the following error
```
Traceback (most recent call last):
  File "/home/toogy/.pyenv/versions/project/bin/pyment", line 11, in <module>
    load_entry_point('Pyment==0.3.2.dev0', 'console_scripts', 'pyment')()
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/pymentapp.py", line 149, in main
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/pymentapp.py", line 98, in run
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/pyment.py", line 333, in proceed
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/docstring.py", line 1942, in generate_docs
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/docstring.py", line 1701, in _set_other
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/docstring.py", line 308, in get_raw_not_managed
AttributeError: 'NoneType' object has no attribute 'split'
```

I think the `numpydoc` support is broken!

**edit**: I checked and this is also happening with `Python 3.5.2`

### PR DESCRIPTION
**Pull request by tgy**
I'm not sure about that but this workaround makes it work.

### CODE REVIEW

**Comment by dadadel** [comment]
Thanks @tgy !
May I suggest you to update your PR to check in case `None` and if `self.docs['out']['post']` is also `None` to set an empty string.

**Comment by tgy** [comment]
There is a problem. Running pyment with my fix (with or without your suggestion) on this file
```python
def hello_world(a=22, b='hello'):
  return 42
```

Gives the following patch
```diff
# Patch generated by Pyment v0.3.2

--- a/test.py
+++ b/test.py
@@ -1,2 +1,15 @@
-def hello_world(a=22, b='hello'):
+    '''
+
+    Parameters
+    ----------
+    a :
+         (Default value = 22)
+    b :
+         (Default value = 'hello')
+
+    Returns
+    -------
+
+    
+    '''
   return 42
```

It deletes the first line.

**Comment by dadadel** [comment]
Ouh ! Bad thing ! I should investigate this...

**Comment by dadadel** [comment]
@tgy do you want to fill a new issue for the last problem you pointed ?

**Comment by tgy** [comment]
@dadadel I would love to but are you sure it is not related to my "fix"?

**Comment by dadadel** [comment]
@tgy definitely sure mate :)
Moreover, you mentioned as commit message the issue 10 but it fix the issue 30 !

**Comment by tgy** [comment]
@dadadel alright, I renamed everything and added the extra condition you mentioned. I squashed everything in a single commit for clarity.

**Pull request merged**
